{
 "title": "Peer Study Hub",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Container Resource Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "HTTP Request Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Total Requests per Endpoint",
   "type": "bargauge",
   "description": "Displays the total number of requests received by each endpoint.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_total{route!=\"/auth/health\", route!=\"/auth/refresh\", route!=\"/metrics\" }",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "timeseries",
   "description": "the time that request take's",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(route, method, status) (http_request_duration_seconds_sum{route!=\"/auth/health\", route!=\"/auth/refresh\", route!=\"/friends/pending\"}) / (sum by(route, method, status) (http_request_duration_seconds_count{route!=\"/auth/health\", route!=\"/auth/refresh\", route!=\"/friends/pending\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Online users",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "active_users", "legendFormat": "__auto" }
   ]
  }
 ]
}